# COMP 135 day01: Intro to Numerical Python

A Python-based version of the "Ch 2 lab" from James et al.'s "Introduction to Statistical Learning" textbook

Based on original notebook: https://nbviewer.jupyter.org/github/emredjan/ISL-python/blob/master/labs/lab_02.3_introduction.ipynb

# What to Do

Students should run this notebook locally, interactively modifying cells as needed to understand concepts and have hands-on practice.

Try to make sure you can *predict* what a function will do. Build a mental model of NumPy will make you a better programmer and ML engineer.

Ask questions like:

* what should the result's output type be?
* what should the result's *shape* be?
* what should the result's *values* be?

# Outline

* [Data types](#data_types)
* [Dimension and shape](#dimension_and_shape)
* [Reshaping](#reshaping)
* [Elementwise multiplication](#elementwise_multiplication)
* [Matrix multiplication](#matrix_multiplication)
* [Useful functions](#useful_functions)
-- linspace, logspace
-- arange
-- allclose
* [Reductions](#reductions)
-- min
-- max
-- sum
-- prod
* [Indexing](#indexing)


# Key Takeaways

* Numpy array types (`np.array`) have a DIMENSION, a SHAPE, and a DATA-TYPE (dtype)

* * Know what you are using!

* Consider using standard notation to avoid confusion

* * 1-dim arrays of size N could be named `a_N` or `b_N` instead of `a` or `b`

* * 2-dim arrays of size (M,N) could be named `a_MN` instead of `a`

* * With this notation, it is far more clear that `np.dot(a_MN, b_N)` will work, but `np.dot(a_MN.T, b_N)` will not

* Broadcasting is key

* * See https://numpy.org/doc/stable/user/basics.broadcasting.html

* Always use np.array, avoid np.matrix 

* * Why? Array is more flexible (can be 1-dim, 2-dim, 3-dim, 4-dim, and more!)
* * Also, np.matrix will be deprecated soon <https://numpy.org/doc/stable/reference/generated/numpy.matrix.html>

# Further Reading

* Stefan van der Walt, S. Chris Colbert, Gaël Varoquaux. The NumPy array: a structure for efficientnumerical computation. Computing in Science and Engineering, Institute of Electrical and Electronics Engineers, 2011. 
<https://hal.inria.fr/inria-00564007/document>

* https://realpython.com/numpy-array-programming/


In [1]:
# import numpy (array library)
import numpy as np


# Basic array creation and manipulation

We use `np.array(...)` function to create arrays

In [2]:
x = np.array([1.0, 6.0, 2.4]);
print(x);

[1.  6.  2.4]


In [3]:
x + 2 # basic element-wise addition

array([3. , 8. , 4.4])

In [4]:
x * 2 # basic element-wise multiplication

array([ 2. , 12. ,  4.8])

In [5]:
x / 2 # basic element-wise division

array([0.5, 3. , 1.2])

In [6]:
x + x # can operate on two arrays of SAME size

array([ 2. , 12. ,  4.8])

In [7]:
x / x # element-wise division

array([1., 1., 1.])

<a id="data_types"></a>

# Data types

Arrays have *data types* (or "dtypes")

In [8]:
y = np.array([1., 4, 3]) # with decimal point in "1.", defaults to 'float' type
print(y)
print(y.dtype)

[1. 4. 3.]
float64


In [9]:
y_int = np.array([1, 4, 3]) # without decimal point, defaults to 'int' type
print(y_int)
print(y_int.dtype)

[1 4 3]
int64


In [10]:
y_float32 = np.array([1, 4, 3], dtype=np.float32) # use optional keyword argument (aka 'kwarg') to specify data type
print(y_float32)
print(y_float32.dtype)

[1. 4. 3.]
float32


In [11]:
z = y + y_float32 # What happens when you add float32 to float64? *upcast* to highest precision
print(z)
print(z.dtype)

[2. 8. 6.]
float64


<a id="dimension_and_shape"></a>

# Dimension and Shape

Arrays have DIMENSION and SHAPE

Dimension = an integer value : number of integers needed to index a unique entry of the array

Shape = a tuple of integers : each entry gives the size of the corresponding dimension


In [12]:
y.ndim

1

In [13]:
y.shape

(3,)

In [14]:
# Create 2D 3x3 array 'M' as floats
M = np.asarray([[1, 4, 7.0], [2, 5, 8], [3, 6, 9]])
print(M)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [15]:
print(M.ndim)

2


In [16]:
print(M.shape)

(3, 3)


In [17]:
# Create 2D *rectangular* array
M_35 = np.asarray([[1, 4, 7.0, 10, 13], [2, 5, 8, 11, 14], [3, 6, 9, 12, 15]])
print(M_35)

[[ 1.  4.  7. 10. 13.]
 [ 2.  5.  8. 11. 14.]
 [ 3.  6.  9. 12. 15.]]


<a id="reshaping"></a>

# Reshaping

Sometimes, we want to transforming from 1-dim to 2-dim arrays

We can either use:
* the *reshape* function
* indexing with the "np.newaxis" built-in <https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis>


#### Demo of reshape

In [18]:
y = np.array([1.0, 4, 3])
print(y)
print(y.shape)

[1. 4. 3.]
(3,)


In [19]:
y_13 = np.reshape(y, (1,3))  # use '_AB' suffix to denote an array with shape (A, B)
print(y_13)
print(y_13.shape)

[[1. 4. 3.]]
(1, 3)


In [20]:
y_31 = np.reshape(y, (3, 1))  # use '_AB' suffix to denote an array with shape (A, B)
print(y_31)
print(y_31.shape)

[[1.]
 [4.]
 [3.]]
(3, 1)


#### Demo of newaxis

In [21]:
y = np.array([1.0, 4, 3])
print(y)
print(y.shape)

[1. 4. 3.]
(3,)


In [22]:
y_13 = y[np.newaxis,:]  # use '_AB' suffix to denote an array with shape (A, B)
print(y_13)
print(y_13.shape)

[[1. 4. 3.]]
(1, 3)


In [23]:
y_31 = y[:, np.newaxis]  # use '_AB' suffix to denote an array with shape (A, B)
print(y_31)
print(y_31.shape)

[[1.]
 [4.]
 [3.]]
(3, 1)


In [24]:
y_311 = y[:, np.newaxis, np.newaxis]  # use '_AB' suffix to denote an array with shape (A, B)
print(y_311)
print(y_311.shape)

[[[1.]]

 [[4.]]

 [[3.]]]
(3, 1, 1)


<a id="elementwise_multiplication"></a>

# Elementwise Multiplication

To perform *element-wise* multiplication, use '*' symbol

In [25]:
print(y)

[1. 4. 3.]


In [26]:
print(M)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [27]:
R = M * M
print(R)

[[ 1. 16. 49.]
 [ 4. 25. 64.]
 [ 9. 36. 81.]]


In [28]:
# What happens when we multiply (3,3) shape by a (3,) shape?
# y is implicitly expanded to (1,3) and thus multiplied element-wise to each row

In [29]:
M * y

array([[ 1., 16., 21.],
       [ 2., 20., 24.],
       [ 3., 24., 27.]])

In [30]:
M * y[np.newaxis,:]

array([[ 1., 16., 21.],
       [ 2., 20., 24.],
       [ 3., 24., 27.]])

In [31]:
M * y[:,np.newaxis]  # this makes y multiplied to each column

array([[ 1.,  4.,  7.],
       [ 8., 20., 32.],
       [ 9., 18., 27.]])

In NumPy, multiplying an (M,N) array by an (M,) array is known as *broadcasting*

NumPy's implicit rules for what happens are defined here:

https://numpy.org/doc/stable/user/basics.broadcasting.html

<a id="matrix_multiplication"></a>

# Matrix multiplication

To do matrix multiplication, use np.dot

In [32]:
np.dot(M, y)

array([38., 46., 54.])

In [33]:
np.dot(M, M)

array([[ 30.,  66., 102.],
       [ 36.,  81., 126.],
       [ 42.,  96., 150.]])

In [34]:
np.dot(y,y) # when applied to a 1-dim array, this is an inner product

26.0

In [35]:
np.dot(y[np.newaxis,:], y[:,np.newaxis])

array([[26.]])

In [36]:
np.sum(np.square(y))

26.0

<a id="pseudorandom_number_generation"></a>

# Pseudorandom number generation

In [37]:
x = np.random.uniform(size=15) # Float values uniformly distributed between 0 and 1
print(x)

[0.8744267  0.92437062 0.098676   0.3290606  0.14743197 0.19825517
 0.62599176 0.13813971 0.06363567 0.86511243 0.89302404 0.20260718
 0.47154504 0.68058636 0.78714028]


In [38]:
x = np.random.normal(size=15) # Float values normally distributed according to 'standard' normal (mean 0, variance 1)
print(x)

[-0.82850445 -0.05456489 -2.89224231  2.05042735  1.20496468  0.32140382
 -0.68193316  0.5156439   0.73909961 -1.44870244 -0.63102067  1.06506266
 -1.72017559 -0.22623301  0.64069298]


To make *repeatable* pseudo-randomness, use a generator with the same seed!

In [39]:
seedA = 0
seedB = 1111
prng = np.random.RandomState(seedA)
prng.uniform(size=10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [40]:
prng = np.random.RandomState(seedA)
prng.uniform(size=10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [41]:
prng = np.random.RandomState(seedB)
prng.uniform(size=10)

array([0.0955492 , 0.9250037 , 0.34357342, 0.31047694, 0.00200984,
       0.23559472, 0.23779172, 0.73591587, 0.49546808, 0.78442535])

<a id="useful_functions"></a>

# Useful functions

#### linspace and logspace

In [42]:
# Linearly spaced numbers
x_N = np.linspace(-2, 2, num=5)
for a in x_N:
    print(a)

-2.0
-1.0
0.0
1.0
2.0


In [43]:
# Logarithmically spaced numbers
x_N = np.logspace(-2, 2, base=10, num=5)
for a in x_N:
    print(a)

0.01
0.1
1.0
10.0
100.0


#### arange

In [44]:
# Start at 0 (default), count up by 1 (default) until you get to 4 (exclusive)
x = np.arange(4)
print(x)

[0 1 2 3]


In [45]:
# Start at negative PI, count up by increments of pi/4 until you get to + PI (exclusive)

y = np.arange(start=-np.pi, stop=np.pi, step=np.pi/4)
print(y)

[-3.14159265 -2.35619449 -1.57079633 -0.78539816  0.          0.78539816
  1.57079633  2.35619449]


In [46]:
# Start at negative PI, count up by increments of pi/4 until you get to PI + very small number (exclusive)

y = np.arange(start=-np.pi, stop=np.pi + 0.0000001, step=np.pi/4)
print(y)

[-3.14159265 -2.35619449 -1.57079633 -0.78539816  0.          0.78539816
  1.57079633  2.35619449  3.14159265]


#### allclose

Useful when checking if entries in an array are "close enough" to some reference value

E.g. sometimes due to numerical issues of representation, we would consider 5.00002 as good as "5"

In [47]:
x_N = np.arange(4)
print(x_N)

[0 1 2 3]


In [48]:
x2_N = x_N + 0.000001
print(x2_N)

[1.000000e-06 1.000001e+00 2.000001e+00 3.000001e+00]


In [49]:
np.all(x_N == x2_N)

False

In [50]:
np.allclose(x_N, x2_N, atol=0.01) # 'atol' is *absolute tolerance*

True

In [51]:
np.allclose(x_N, x2_N, atol=1e-7) # trying with too small a tolerance will result in False

False

<a id="reductions"></a>

# Reductions

Some numpy functions like 'sum' or 'prod' or 'max' or 'min' that take in many values and produce fewer values.

These kinds of operations are known as "reductions".

Within numpy, any reduction function takes an optional 'axis' kwarg to specify specific dimensions to apply the reduction to


In [52]:
# 2D array creation
# R equivalent of matrix(1:16, 4 ,4))
A = np.arange(1, 17).reshape(4, 4).transpose()
A

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [53]:
np.sum(A) # sum of all entries of A

136

In [54]:
np.sum(A, axis=0) # sum across dim with index 0 (across rows)

array([10, 26, 42, 58])

In [55]:
np.sum(A, axis=1) # sum across dim with index 1 (across cols)

array([28, 32, 36, 40])

In [56]:
np.min(A, axis=1) # compute minimum across dim with index 1

array([1, 2, 3, 4])

<a id="indexing"></a>

# Indexing

In [57]:
# 2D array creation
# R equivalent of matrix(1:16, 4 ,4))
A = np.arange(1, 17).reshape(4, 4).transpose()
A

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [58]:
# Show the first row
A[0]

array([ 1,  5,  9, 13])

In [59]:
# Show the first col
A[:, 0]

array([1, 2, 3, 4])

In [60]:
# Grab the second row, third column
A[1,2]

10

In [61]:
# select a range of rows and columns
A[0:3, 1:4]


array([[ 5,  9, 13],
       [ 6, 10, 14],
       [ 7, 11, 15]])

In [62]:
# select a range of rows and all columns
A[0:2,:]

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14]])

In [63]:
# select the *last* row
A[-1]

array([ 4,  8, 12, 16])

In [64]:
# select the *second to last* column
A[:, -2]

array([ 9, 10, 11, 12])